name: Crash Report
description: Software aborted or outright crashed
title: "[Crash] Short summary of the context"
labels: ["bug", "crash"]
body:
  - type: input
    id: sys-ver
    attributes:
      label: System Firmware Version
      description: The system version installed on your Nintendo Switch.
      placeholder: ex. 11.0.1
    validations:
      required: true
  - type: input
    id: ams-ver
    attributes:
      label: Atmosphere Version
      description: The version of Atmosphere currently installed on your Nintendo Switch.
      placeholder: ex. 0.18.1
    validations:
      required: true
  - type: input
    id: smash-ver
    attributes:
      label: Smash Version
      description: The version of Smash Ultimate currently installed on your Nintendo Switch (Press + on the icon on the home menu).
      placeholder: ex. 13.0.0
    validations:
      required: true
  - type: input
    id: arc-ver
    attributes:
      label: ARCropolis Version
      description: The version of ARCropolis you are currently running (check the title screen if you can reach it).
      placeholder: ex. 2.1.1
    validations:
      required: true
  - type: dropdown
    id: upd-channel
    attributes:
      label: Version channel
      description: What version channel of ARCropolis are you running?
      options:
        - Stable
        - Beta
    validations:
      required: true
  - type: dropdown
    id: sd-format
    attributes:
      label: SD card formatting
      options:
        - FAT32
        - exFat
    validations:
      required: true
  - type: dropdown
    id: reproducibility
    attributes:
      label: Can the crash be consistently reproduced?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: checkboxes
    id: config
    attributes:
      label: Configuration
      description: Check the relevant boxes
      options:
      - label: Legacy discovery
      - label: Modern discovery (>= 3.0.0)
      - label: Irrelevant/Not provided
  - type: checkboxes
    id: crash-timing
    attributes:
      label: At what moment does the crash happen?
      description: You may select more than one. Please provide more information in the Context field below.
      options:
        - label: Before the Switch boot animation
        - label: After the Switch boot animation
        - label: During the Smash ball loading on boot
        - label: Before the opening cutscene, but only sometimes
        - label: On the Stage Select Screen
        - label: On the Character Select Screen
        - label: During the loading for a battle
        - label: At random
        - label: After a long time playing
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide more details, such as the steps to take to reproduce the crash
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: Crash report
      description: Get the most recent ``.log`` file from ``sd:/atmosphere/crash_reports/`` right after the crash and post the first ~100 lines
      render: shell
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Minimal modpack to reproduce the crash
      description: If a specific set of mods is necessary to reproduce the crash, please provide it
