name: Feature suggestion
description: Suggest a new feature for ARCropolis
title: "[Feature suggestion] Brief description of the suggestion"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # DISCLAIMER
        Do note that suggestions are only going to be considered for upcoming versions. No feature is going to be backported to an older version (i.e. ``0.9.6``).
  - type: checkboxes
    id: disclaimer-read
    attributes:
      label: Have you read the disclaimer before proceeding?
      options:
        - label: I have read the disclaimer.
          required: true
  - type: textarea
    id: suggestion
    attributes:
      label: What would the feature do?
      description: Please explain what the feature should be in a short and clear description.
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: How should it be implemented?
      description: Describe how you'd like the feature to work, if necessary.
