name: build_nightly
on: 
  workflow_dispatch:

jobs:
  plugin_build:
    env:
      PLUGIN_NAME: ARCropolis
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:2.1.0-dkp
    steps:
    - name: checkout version
      uses: actions/checkout@v2

    # build the project
    - run: |
        export PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin \
        && cargo skyline build --release --no-default-features
      env:
        HOME: /root

    - name: find the plugin
      run: |
        find ./target/ -name *.nro
        cp $(find ./target/ -name *.nro) .


    - name: Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: libarcropolis.nro